export const FILTER_CHECKOUT_PRICE = 'FILTER_CHECKOUT_PRICE'

export const FILTER_PAYLINK_POST_DATA = 'FILTER_PAYLINK_POST_DATA'

export const FILTER_MENU_GROUPS = 'FILTER_MENU_GROUPS'

export const FILTER_SIGNUP_DATA = 'FILTER_SIGNUP_DATA'

export const FILTER_SUBSCRIPTION_PLAN_FREQUENCIES =
    'FILTER_SUBSCRIPTION_PLAN_FREQUENCIES'

export const FILTER_DASHBOARD_LIST_CREATE_BUTTON =
    'FILTER_DASHBOARD_LIST_CREATE_BUTTON'

export const FILTER_WEBSITE_BUILDER_FULLSCREEN_TEXT_COLOR =
    'FILTER_WEBSITE_BUILDER_FULLSCREEN_TEXT_COLOR'

export const FILTER_AFTER_LOGIN_SHOULD_DO_REDIRECT =
    'FILTER_AFTER_LOGIN_SHOULD_DO_REDIRECT'

export const FILTER_DASHBOARD_LIST_SHOULD_RENDER_BULK_CREATE_BUTTON =
    'FILTER_DASHBOARD_LIST_SHOULD_RENDER_BULK_CREATE_BUTTON'

export const FILTER_QRCODE_FORM_CHANGE_TYPE_BUTTON =
    'FILTER_QRCODE_FORM_CHANGE_TYPE_BUTTON'

export const FILTER_QRCODE_LINK_SHOULD_RENDER_SETTINGS_ICON =
    'FILTER_QRCODE_LINK_SHOULD_RENDER_SETTINGS_ICON'

export const FILTER_QRCODE_FORM_SHOULD_RENDER_SAVE_AS_TEMPLATE_BUTTON =
    'FILTER_QRCODE_FORM_SHOULD_RENDER_SAVE_AS_TEMPLATE_BUTTON'

export const FILTER_QRCODE_ROW_COPY = 'FILTER_QRCODE_ROW_COPY'

export const FILTER_QRCODE_ROW_ARCHIVE = 'FILTER_QRCODE_ROW_ARCHIVE'

export const FILTER_QRCODE_ROW_FOLDERS_LINK = 'FILTER_QRCODE_ROW_FOLDERS_LINK'

export const FILTER_QRCODE_ROW_SHOULD_DO_ACT_AS =
    'FILTER_QRCODE_ROW_SHOULD_DO_ACT_AS'

export const FILTER_QRCODE_TYPES = 'FILTER_QRCODE_TYPES'

export const FILTER_QRCODE_TYPES_CLASS_LIST = 'FILTER_QRCODE_TYPES_CLASS_LIST'
