export const ACTION_CHECKOUT_ABOVE_PAYMENT_PROCESSORS_TAB =
    'ACTION_CHECKOUT_ABOVE_PAYMENT_PROCESSORS_TAB'

export const ACTION_MY_ACCOUNT_BELOW_SUBSCRIPTION_MANAGEMENT =
    'ACTION_MY_ACCOUNT_BELOW_SUBSCRIPTION_MANAGEMENT'

export const ACTION_LEAD_FORM_AFTER_STARS_QUESTION =
    'ACTION_LEAD_FORM_AFTER_STARS_QUESTION'

export const ACTION_QRCODE_ROW_ACTIONS = 'ACTION_QRCODE_ROW_ACTIONS'
