import { kebabCase } from '../core/helpers'

export const qrShapes = [
    'None',
    'Circle',
    'Cloud',
    'Shopping Cart',
    'Gift',
    'Cup',
    'T-Shirt',
    'Home',
    'Book',
    'Message',
    'Bag',
    'Truck',
    'Trophy',
    'Umbrella',
    'Van',
    'Watch',
    'Water',
    'Bulb',
    'Sun',
    'Car',
    'Pet',
    'GYM',
    'Salon',
    'Food',
    'Ice Cream',
    'Search',
    'Burger',
    'Apple',
    'Barn',
    'Sun Rise',
    'Star',
    'Realtor',
    'Legal',
    'Juice',
    'Water Glass',
    'Electrician',
    'Plumber',
    'Builder',
    'Home Mover',
    'Cooking',
    'Gardening',
    'Furniture',
    'Mobile',
    'Restaurant',
    'Travel',
    'Dentist',
    'Golf',
    'Pizza',
    'Locksmith',
    'Bakery',
    'Painter',
    'Pest',
    'Teddy',
    'Boot',
    'Shield',
    'Shawarma',
    'Ticket',
    'Piggy Bank',
    'Realtor Sign',
].map((name) => {
    return {
        name,
        value: kebabCase(name),
    }
})
